"""
events.py
Workflow Side-Effects — Hostel Management PSM

Triggered AFTER service execution.
Derived from WF-101 → WF-113.
"""

from datetime import date, timedelta, datetime
from typing import List

from .models import (
    AttendanceRecord,
    NoticeReadStatus,
    SystemAuditLog
)


# =====================================================
# WF-101 — LEAVE EVENTS
# =====================================================

def update_attendance_on_leave(attendance: AttendanceRecord,
                               start_date: date,
                               end_date: date):
    current = start_date
    while current <= end_date:
        attendance.dates.append(current)
        current += timedelta(days=1)
    attendance.on_leave = True


def audit_leave_action(actor_id: str, action: str):
    return SystemAuditLog(
        log_id=f"AUD-{datetime.now().timestamp()}",
        details=f"Leave {action} by {actor_id}"
    )


# =====================================================
# WF-102 — COMPLAINT EVENTS
# =====================================================

def audit_complaint_resolution(actor_id: str, complaint_id: str):
    return SystemAuditLog(
        log_id=f"AUD-{datetime.now().timestamp()}",
        details=f"Complaint {complaint_id} resolved by {actor_id}"
    )


# =====================================================
# WF-104 — ROOM CHANGE EVENTS
# =====================================================

def audit_room_change(student_id: str, old_room: str, new_room: str):
    return SystemAuditLog(
        log_id=f"AUD-{datetime.now().timestamp()}",
        details=f"Room changed for {student_id}: {old_room} → {new_room}"
    )


# =====================================================
# WF-109 — ROOM VACATION EVENTS
# =====================================================

def audit_room_vacation(student_id: str):
    return SystemAuditLog(
        log_id=f"AUD-{datetime.now().timestamp()}",
        details=f"Room vacated by {student_id}"
    )


# =====================================================
# WF-110 — NOTICE EVENTS
# =====================================================

def mark_notice_read(notice_id: str, student_id: str) -> NoticeReadStatus:
    return NoticeReadStatus(
        notice_id=notice_id,
        student_id=student_id
    )


# =====================================================
# WF-111 — REPORT EVENTS
# =====================================================

def audit_report_generation(actor_id: str, report_id: str):
    return SystemAuditLog(
        log_id=f"AUD-{datetime.now().timestamp()}",
        details=f"Report {report_id} generated by {actor_id}"
    )
