"""
events.py
Workflow Side-Effects — Hostel Management PSM

Triggered AFTER service execution.
Derived from WF-101 → WF-113.
"""

from datetime import date, timedelta, datetime
from typing import List

from .models import (
    AttendanceRecord,
    NoticeReadStatus,
    SystemAuditLog
)


# =====================================================
# WF-101 — LEAVE EVENTS
# =====================================================

def update_attendance_on_leave(attendance: AttendanceRecord,
                               start_date: date,
                               end_date: date):
    current = start_date
    while current <= end_date:
        attendance.dates.append(current)
        current += timedelta(days=1)
    attendance.on_leave = True


def audit_leave_action(actor_id: str, action: str):
    return SystemAuditLog(
        log_id=f"AUD-{datetime.now().timestamp()}",
        details=f"Leave {action} by {actor_id}"
    )


# =====================================================
# WF-102 — COMPLAINT EVENTS
# =====================================================

def audit_complaint_resolution(actor_id: str, complaint_id: str):
    return SystemAuditLog(
        log_id=f"AUD-{datetime.now().timestamp()}",
        details=f"Complaint {complaint_id} resolved by {actor_id}"
    )


# =====================================================
# WF-104 — ROOM CHANGE EVENTS
# =====================================================

def audit_room_change(student_id: str, old_room: str, new_room: str):
    return SystemAuditLog(
        log_id=f"AUD-{datetime.now().timestamp()}",
        details=f"Room changed for {student_id}: {old_room} → {new_room}"
    )


# =====================================================
# WF-109 — ROOM VACATION EVENTS
# =====================================================

def audit_room_vacation(student_id: str):
    return SystemAuditLog(
        log_id=f"AUD-{datetime.now().timestamp()}",
        details=f"Room vacated by {student_id}"
    )


# =====================================================
# WF-110 — NOTICE EVENTS
# =====================================================

def mark_notice_read(notice_id: str, student_id: str) -> NoticeReadStatus:
    return NoticeReadStatus(
        notice_id=notice_id,
        student_id=student_id
    )


# =====================================================
# WF-111 — REPORT EVENTS
# =====================================================

def audit_report_generation(actor_id: str, report_id: str):
    return SystemAuditLog(
        log_id=f"AUD-{datetime.now().timestamp()}",
        details=f"Report {report_id} generated by {actor_id}"
    )


# ======================================================
# ======================================================

# =====================================================
# WF-103 — ROOM ALLOTMENT EVENTS
# =====================================================

def audit_room_allotment(student_id: str, room_id: str):
    """Audit room allocation"""
    return SystemAuditLog(
        log_id=f"AUD-{datetime.now().timestamp()}",
        details=f"Room {room_id} allocated to {student_id}"
    )


def notify_student_allotment(student_id: str, room_id: str):
    """Notify student of room allocation"""
    return NoticeReadStatus(
        notice_id=f"ALLOT-{room_id}",
        student_id=student_id
    )


# =====================================================
# WF-104 — ROOM CHANGE EVENTS (ENHANCED)
# =====================================================

def notify_student_room_change(student_id: str, old_room: str, new_room: str):
    """Notify student of approved room change"""
    return SystemAuditLog(
        log_id=f"AUD-{datetime.now().timestamp()}",
        details=f"Student {student_id} notified: Room change from {old_room} to {new_room}"
    )


# =====================================================
# WF-106 — HOSTEL SETUP EVENTS
# =====================================================

def audit_hostel_creation(hostel_id: str, admin_id: str):
    """Audit hostel creation"""
    return SystemAuditLog(
        log_id=f"AUD-{datetime.now().timestamp()}",
        details=f"Hostel {hostel_id} created by {admin_id}"
    )


def audit_staff_assignment(staff_id: str, hostel_id: str, role: str):
    """Audit staff assignment"""
    return SystemAuditLog(
        log_id=f"AUD-{datetime.now().timestamp()}",
        details=f"Staff {staff_id} assigned as {role} to {hostel_id}"
    )


def audit_hostel_activation(hostel_id: str):
    """Audit hostel activation"""
    return SystemAuditLog(
        log_id=f"AUD-{datetime.now().timestamp()}",
        details=f"Hostel {hostel_id} activated and operational"
    )


# =====================================================
# WF-107 — SECURITY EVENTS
# =====================================================

def audit_guard_assignment(guard_id: str, shift_id: str):
    """Audit guard shift assignment"""
    return SystemAuditLog(
        log_id=f"AUD-{datetime.now().timestamp()}",
        details=f"Guard {guard_id} assigned to shift {shift_id}"
    )


def audit_incident_report(incident_id: str, severity: str):
    """Audit security incident"""
    return SystemAuditLog(
        log_id=f"AUD-{datetime.now().timestamp()}",
        details=f"Security incident {incident_id} logged with severity {severity}"
    )


# =====================================================
# WF-108 — VISITOR EVENTS
# =====================================================

def audit_visitor_entry(visitor_name: str, log_id: str):
    """Audit visitor entry"""
    return SystemAuditLog(
        log_id=f"AUD-{datetime.now().timestamp()}",
        details=f"Visitor {visitor_name} entered - Log ID: {log_id}"
    )


def audit_visitor_exit(visitor_name: str, log_id: str):
    """Audit visitor exit"""
    return SystemAuditLog(
        log_id=f"AUD-{datetime.now().timestamp()}",
        details=f"Visitor {visitor_name} exited - Log ID: {log_id}"
    )


def notify_visitor_approval(student_id: str, request_id: str, approved: bool):
    """Notify student of visitor request decision"""
    status = "approved" if approved else "rejected"
    return SystemAuditLog(
        log_id=f"AUD-{datetime.now().timestamp()}",
        details=f"Visitor request {request_id} {status} for student {student_id}"
    )


# =====================================================
# WF-109 — ROOM VACATION EVENTS (ENHANCED)
# =====================================================

def audit_clearance_verification(student_id: str, department: str):
    """Audit department clearance"""
    return SystemAuditLog(
        log_id=f"AUD-{datetime.now().timestamp()}",
        details=f"Clearance verified for {student_id} by {department}"
    )


def notify_vacation_approval(student_id: str, request_id: str):
    """Notify student of vacation approval"""
    return SystemAuditLog(
        log_id=f"AUD-{datetime.now().timestamp()}",
        details=f"Room vacation approved for {student_id} - Request: {request_id}"
    )


# =====================================================
# WF-112 — GUEST ROOM EVENTS
# =====================================================

def audit_guest_booking(booking_id: str, student_id: str):
    """Audit guest room booking"""
    return SystemAuditLog(
        log_id=f"AUD-{datetime.now().timestamp()}",
        details=f"Guest room booking {booking_id} created by {student_id}"
    )


def audit_guest_checkin(booking_id: str, guest_name: str):
    """Audit guest check-in"""
    return SystemAuditLog(
        log_id=f"AUD-{datetime.now().timestamp()}",
        details=f"Guest {guest_name} checked in - Booking: {booking_id}"
    )


def audit_guest_checkout(booking_id: str, damages_found: bool):
    """Audit guest checkout"""
    damage_status = "with damages" if damages_found else "without damages"
    return SystemAuditLog(
        log_id=f"AUD-{datetime.now().timestamp()}",
        details=f"Guest checked out {damage_status} - Booking: {booking_id}"
    )


# =====================================================
# WF-113 — EXTENDED STAY EVENTS
# =====================================================

def audit_extended_stay_application(application_id: str, student_id: str):
    """Audit extended stay application"""
    return SystemAuditLog(
        log_id=f"AUD-{datetime.now().timestamp()}",
        details=f"Extended stay application {application_id} submitted by {student_id}"
    )


def audit_extended_stay_review(application_id: str, approved: bool, reviewer: str):
    """Audit extended stay review"""
    decision = "approved" if approved else "rejected"
    return SystemAuditLog(
        log_id=f"AUD-{datetime.now().timestamp()}",
        details=f"Extended stay {application_id} {decision} by {reviewer}"
    )


def audit_extended_stay_payment(application_id: str, payment_received: bool):
    """Audit extended stay payment"""
    status = "received" if payment_received else "pending"
    return SystemAuditLog(
        log_id=f"AUD-{datetime.now().timestamp()}",
        details=f"Payment {status} for extended stay {application_id}"
    )


def notify_extended_stay_approval(student_id: str, application_id: str, approved: bool):
    """Notify student of extended stay decision"""
    decision = "approved" if approved else "rejected"
    return SystemAuditLog(
        log_id=f"AUD-{datetime.now().timestamp()}",
        details=f"Student {student_id} notified: Extended stay {decision} - App: {application_id}"
    )
